.nh
.TH rpt 1 "" "" "rpt Manual"

.SH NAME
rpt \- run the given command the given number of times


.SH SYNOPSIS
.EX
rpt [OPTIONS] TIMES COMMAND [ARGUMENTS...]
.EE


.SH DESCRIPTION
Run \fBCOMMAND ARGUMENTS\fR TIMES times.


.SH OPTIONS
.TP
\fB--fail-fast\fP
if command fails exit immediately with the same exit code as command.

.TP
\fB-d=DURATION, --delay=DURATION\fP
wait \fBDURATION\fR between runs (default: 0s)

.TP
\fB-v, --verbose\fP
print debugging messages


.SH AUTHOR
Ben Armston


.SH COPYRIGHT
Copyright 2025 Ben Armston. Licensed under the MIT License.
