on:
  push:
    branches: [main]
    paths-ignore: ['docs/**']
  pull_request:
    branches: [main]
    paths-ignore: ['docs/**']

name: Build, lint and test
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    strategy:
      fail-fast: true
      matrix:
        go: ['1.23.x']
        os: [ubuntu-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Go Tidy
        run: go mod tidy && git diff --exit-code

      - name: Go Mod
        run: go mod download

      - name: Go Mod Verify
        run: go mod verify

      - name: Go Build
        run: go build

  test:
    name: Test
    needs: build
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    strategy:
      fail-fast: true
      matrix:
        go: [1.23.x]
        os: [ubuntu-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Go Test
        # run: go test -v -count=1 -race -shuffle=on -coverprofile=coverage.txt ./...
        run: go test -v -count=1 -race -shuffle=on ./...

      # - name: Go Benchmark
      #   run: go test -v -shuffle=on -run=- -bench=. -benchtime=1x ./...

  linters:
    name: Run linters et al
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        go: [1.23.x]
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          # Optional: golangci-lint command line arguments.
          #args:
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true

      - name: Go Format
        run: gofmt -s -w . && git diff --exit-code

      - name: Go Vet
        run: go vet ./...

      - name: Check docs
        run: go run -tags docs ./docs/ && git diff --exit-code
